[package]
name = "ethui-proxy-detect"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.11.0", default-features = false, features = [
  "providers",
  "reqwest-rustls-tls",
  "rpc",
  "rpc-types",
] }
thiserror = "2"

[dev-dependencies]
rstest = "0.24.0"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
lazy_static = "1.5.0"
